version: '3'
networks:
  default:
    name: app_network
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana-container
    ports:
      - "3000:3000"
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml